query MergeConcreteTypeInRootFieldAndInterfaceFragment {
    productA {
        bundle {
            id
            bundleName
        }
        ... on Base {
            ...ProductDetail
        }
    }
}

fragment ProductDetail on Base {
    ... on ProductB {
        bundle {
            displayOwner: bundleOwner {
                ownerName
            }
            bundleOwners { ownerName }
            bundleRelation { id bundleName }
        }
    }
    ... on ProductA {
        bundle {
            displayOwner: bundleOwner {
                ownerName
            }
            bundleOwners { ownerName }
            bundleRelation { id bundleName }
        }
    }
}
